# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [fasfa, nextstar]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://one.org','https://open.spotify.com/playlist/37i9dQZF1DZ06evO2lQQ36?si=WjKG17_HSz62zrK8iKPdrw','https://whois.nit','https://mad.org', 'https://hunters.io']
